language: csharp
dist: precise
mono: none
dotnet: 2.0.0

solution: ./VkNet.UWP.sln

install:
  - sudo apt-get install nunit-console

script:
  - dotnet restore ./VkNet.UWP.sln
  - dotnet build ./VkNet.UWP.sln
  - nunit-console ./Debug/VkNet.Tests.dll
