language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1

solution: ./VkNet.UWP.sln

install:
  - sudo apt-get install nunit-console

script:
  - dotnet restore && dotnet build ./VkNet.UWP.sln
  - nunit-console ./Debug/VkNet.Tests.dll
