# markdown: rdiscount
 markdown: redcarpet
#markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

# site
url: https://vknet.github.io/vk
