# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  BuildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: 'VkNet/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: 'VkNet/*.csproj'

    arguments: '--configuration $(BuildConfiguration) --no-restore'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test

    projects: 'VkNet/*[Tt]ests/*.csproj'

    arguments: '--configuration $(BuildConfiguration) --no-restore' 
