# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Hosted VS2017'

variables:
  BuildConfiguration: 'Release'
  Parameters.CanPush: true

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.402'
  inputs:
    version: 2.1.402
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test

    projects: '*[Tt]ests/*.csproj'

    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: custom
	
	projects: VkNet/VkNet.csproj

    custom: pack

    arguments: '-o $(Build.ArtifactStagingDirectory) -c "$(BuildConfiguration)" --version-suffix $(Build.BuildId)'
- task: DotNetCoreCLI@2
  displayName: 'Push to MyGet'
  inputs:
    command: custom

    custom: 'nuget push'

    arguments: '*.nupkg -k $(Parameters.MyGetKey) -s $(Parameters.MyGetFeed)'

    workingDirectory: '$(Build.ArtifactStagingDirectory)'

  enabled: true

- task: EvgenyChernyi.telegram-notification-extension.sample-telegram-task.SendTelegramNotification@0
  displayName: 'Send Telegram Notification'
  inputs:
    botToken: '$(Parameters.botToken)'

    chats: '$(Parameters.chats)'

    message: '<code>Reason: $(Build.Reason) 
	Build №: $(Build.BuildNumber)
	VkNet был успешно собран!</code>'

    buildQueuedBy: true
